# Generated by Django 5.0.5 on 2024-05-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='testfield',
            field=models.CharField(default='kenyakuu', max_length=100),
        ),
    ]
