# Generated by Django 5.0.5 on 2024-05-08 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='testfield',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
    ]
