# Generated by Django 5.0.5 on 2024-05-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonalEvents',
            new_name='SeasonalEvent',
        ),
    ]
